name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui matplotlib scipy seaborn

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=app_icon.ico --name CriticalRValueConfidence CriticalRValueConfidence.py --hidden-import=pyautogui

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: CriticalRValueConfidence.exe
          path: dist/CriticalRValueConfidence.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/CriticalRValueConfidence.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
